### ISSUE TITLE
Matplotlib deprecation

### ISSUE THREAD

**Issue by oigroig** [networkx/networkx#2407]
Simply running

    import networkx as 
    G = nx.Graph()
    nx.draw(G)

gives the following warning:

```
/usr/local/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py:125: MatplotlibDeprecationWarning: pyplot.hold is deprecated.
    Future behavior will be consistent with the long-time default:
    plot commands add elements without first clearing the
    Axes and/or Figure.
  b = plt.ishold()
/usr/local/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py:137: MatplotlibDeprecationWarning: pyplot.hold is deprecated.
    Future behavior will be consistent with the long-time default:
    plot commands add elements without first clearing the
    Axes and/or Figure.
  plt.hold(b)
/Users/giorgiogiuffre/Library/Python/3.6/lib/python/site-packages/matplotlib/__init__.py:917: UserWarning: axes.hold is deprecated. Please remove it from your matplotlibrc and/or style files.
  warnings.warn(self.msg_depr_set % key)
/Users/giorgiogiuffre/Library/Python/3.6/lib/python/site-packages/matplotlib/rcsetup.py:152: UserWarning: axes.hold is deprecated, will be removed in 3.0
  warnings.warn("axes.hold is deprecated, will be removed in 3.0")
```

... but, according to [this answer on SO](http://stackoverflow.com/questions/42295599/networkx-draw-graph-deprecated-message#42630341), the warning disappears if you leave out the lines using `pyplot.hold()`.

**Comment by MridulS** [comment]
Thanks for the report. The issue https://github.com/networkx/networkx/issues/2342 and it's proposed fix https://github.com/networkx/networkx/pull/2397

@oigroig You can just neglect these warnings right now :)

**Comment by oigroig** [comment]
Ok, thank you.

**Comment by hagberg** [comment]
Fixed in #2397

**Comment by ricardojumia** [comment]
This issue still exists in the latest version.
From Jupyter (I'm using conda):

> C:\ProgramData\Anaconda3\lib\site-packages\networkx\drawing\nx_pylab.py:611: **MatplotlibDeprecationWarning**: isinstance(..., numbers.Number)
>   if cb.is_numlike(alpha):

**Comment by dschult** [comment]
There us nothing (in the latest version) on line 611 that would give this kind of error. 
Check your version using ```print(nx.__version__)``` or similar... and let us know.

**Comment by ricardojumia** [comment]
Thanks. I used  `print(nx.__version__)` and the output was 2.2.

**Comment by dschult** [comment]
Thank you -- that helped me see what I was missing...

You added this to an existing Issue about deprecation of ```is_hold``` and ```hold```.  So I missed that your concern is deprecation of ```is_numlike```.  It's probably better to open a new Issue, but this will do fine.

Luckily, changes to address this deprecation are in #3174 and fixed in #3179 
This was after v2.2 and will be in v2.3.
