### ISSUE TITLE
Memory leak in DiGraph and views

### ISSUE THREAD

**Issue by fritzo** [networkx/networkx#2885]
`nx.__version__ == 2.0`

My team is having trouble with memory leaks due to cyclic references in `DiGraph` objects.

I believe this could be fixed by using `weakref`s to store the `self._graph` attribute in all of the `*View` classes in networkx/classes/reportviews.py (e.g. [here](https://github.com/networkx/networkx/blob/master/networkx/classes/reportviews.py#L335)), something like
```diff
  def __init__(self, G):
-     self._graph = G = state[_'graph']
+     G = state['_graph']()
+     self._graph = weakref(G)
```
Does this fix sound reasonable? If so my team might try to implement it.

Related: https://github.com/uber/pyro/issues/798
Related: https://github.com/uber/pyro/pull/801

**Comment by fritzo** [comment]
cc @eb8680

**Comment by dschult** [comment]
This looks quite reasonable. Thank you.

You proposed fix uses the syntax ```G = state['_graph']()``` which will not work because graphs are not callable. Should you call weakref on ```state['_graph']``` directly? Or am I missing something.

      def __init__(self, G):
    -     self._graph = G = state[_'graph']
    +     self._graph = G = weakref(state['_graph'])

**Comment by fritzo** [comment]
The fix I am proposing is to replace `state['_graph']` and `self._graph` with `weakref`s. To read from a weakref, you call it. See [weakref documentation](https://docs.python.org/2/library/weakref.html).

I'm not fully clear about what `state` contains. Does it seem feasible to replace `state['_graph']` with a `weakref` to the graph everywhere?

**Comment by dschult** [comment]
The ```state['_graph']``` syntax is used for pickle and deepcopy where the ```state``` dict holds attributes needed to unpickle the object. I am not very familiar with weakrefs and in particular with pickling weakrefs, but my understanding is that they only impact garbage collection and that special linkage should work fine across pickling.  So, YES it should be fine to replace ```state['_graph']``` with a weak reference to it everywhere. Certainly for self._graph and most likely for ```state['_graph']```

**Comment by eb8680** [comment]
> my understanding is that they only impact garbage collection and that special linkage should work fine across pickling

Are there any networkx unit tests that would fail if this weren't true and the proposed change was made?

**Comment by dschult** [comment]
As far as I know we don't have any tests that specifically look at garbage collection.  We do have unit tests for pickling and un-pickling. So that side of it should be tested by travis-CI automatically.

**Comment by eb8680** [comment]
> We do have unit tests for pickling and un-pickling. So that side of it should be tested by travis-CI automatically

Thanks, this is what I meant.

**Comment by eb8680** [comment]
FYI @dschult we are no longer planning on pushing a fix for this.

**Comment by dschult** [comment]
See #2915

**Comment by dschult** [comment]
Fixed in #3011 
If you could try it and see if the fix worked I'd appreciate it.
Thanks

**Comment by eb8680** [comment]
@dschult will take a look today, thanks!

**Comment by eb8680** [comment]
@dschult hmm, I'm still seeing memory leaks with the `master` branch of `networkx`.  Here are the tests that we use to detect leaks: https://github.com/eb8680/pyro/blob/reinstate-networkx/tests/test_memory.py

If I `git clone https://github.com/eb8680/pyro` and run that test on the `reinstate-networkx` branch, the tests fail.  If I run it on the `dev` branch (which is tracking the main repository), they pass.  The only difference is in this commit: https://github.com/eb8680/pyro/commit/733f1634ee60f7a043e21553c1b4345123a29e60

The `dev` branch wraps the subclass of `networkx.DiGraph`, and the `reinstate-networkx` branch does not.

**Comment by dschult** [comment]
Thanks very much for the test code -- Using ```gc.get_objects()``` I was able to track the garbage collection.  I also recommend ```objgraph``` which I didn't know about before to track the back-references to objects. 

I was able to find the second circular reference =>  G.root_graph
I think that should be fixable -- will try it in a bit.  
Hopefully there won't be any others.

**Comment by eb8680** [comment]
@dschult #3014 seems to have fixed it - the tests linked above pass now.  Thanks for fixing this!

**Comment by dschult** [comment]
I'm aiming for v2.2 release in June or July...
Thanks for your help in tracking this down.
